### ISSUE TITLE
PWR/ACC SMG Scope not Correctly Positioned/Scaled

### ISSUE THREAD

**Issue by theweion** [Alex-231/Halo3HUD-for-HaloOnline#12]
This is running on the Big Screen HUD Scaling Mode.

![11296258317774487552_2016-03-07_00003](https://cloud.githubusercontent.com/assets/6871837/13567724/c8258abc-e454-11e5-83a1-823e9ea2adfc.png)

**Comment by Alex-231** [comment]
Well spotted, probably slipped in with the dual wielding fixes in 1.8. Easy to fix.

**Comment by Alex-231** [comment]
Should be able to get this fixed later today.
