### ISSUE TITLE
The mongoose & warthog's passenger crosshairs goes off center on 1.8.1

### ISSUE THREAD

**Issue by KyouKeiKen** [Alex-231/Halo3HUD-for-HaloOnline#13]
![20160312140327_1](https://cloud.githubusercontent.com/assets/6925024/13720393/7d8fb35a-e85b-11e5-897b-a8a3b0e85b0a.jpg)
![20160312140358_1](https://cloud.githubusercontent.com/assets/6925024/13720394/7d92b53c-e85b-11e5-960d-3d9f5e29c6af.jpg)

**Comment by KyouKeiKen** [comment]
![20160312140327_1](https://cloud.githubusercontent.com/assets/6925024/13720393/7d8fb35a-e85b-11e5-897b-a8a3b0e85b0a.jpg)
![20160312140358_1](https://cloud.githubusercontent.com/assets/6925024/13720394/7d92b53c-e85b-11e5-960d-3d9f5e29c6af.jpg)

**Comment by Alex-231** [comment]
As of 2.0 I no longer need to change these crosshairs, so either it's a default Halo Online issue or it's not an issue.
