### ISSUE TITLE
Just maybe a slight bit of tag corruption going on.

### ISSUE THREAD

**Issue by NoShotz** [Alex-231/Halo3HUD-for-HaloOnline#15]
When i installed the latest version of the mod, the game wouldnt start up, after a few tries, it finally started up, and i got this

http://i.imgur.com/9vidTid.png

**Comment by Alex-231** [comment]
I think I might know why.  If it's as simple as I think I'll patch it sometime after ths 20th.

**Comment by Alex-231** [comment]
I've not experienced this for a long time and I probably fixed it and forgot.
